### ISSUE TITLE
Issue with colors of legend

### ISSUE THREAD

**Issue by josephhughes** [sairum/tcsBU#1]
Hi @sairum,

Really neat tool, it is very useful but I am having issues with the colors in the legend which do not correspond to the colors I have assigned. I've attached a screenshot and the input files.

I'd be really grateful if you could help.
Thanks,
Joseph
<img width="963" alt="screen shot 2015-11-19 at 14 29 43" src="https://cloud.githubusercontent.com/assets/359553/11276276/61284afa-8ed9-11e5-8ce0-d448efd6e3bf.png">
[CalssificationGroups.txt](https://github.com/sairum/tcsBU/files/39162/CalssificationGroups.txt)
[HaplotypeGroups.txt](https://github.com/sairum/tcsBU/files/39161/HaplotypeGroups.txt)
[TCS_network.txt](https://github.com/sairum/tcsBU/files/39166/TCS_network.txt)

**Comment by sairum** [comment]
Dear Joseph

I'm in a middle of an MSc course, 9-18h daily, 5 days week! It ends 
tomorrow. I'll look at this as soon as possible!
Regards

Antoio

**Comment by sairum** [comment]
Hi

A very strange bug! I still have to know what causes it. The thing is 
that in your "CalssificationGroups.txt" you have

L1420;#B2DF8A
L2761;#FFD92F
L1420;#E7298A
L6273;#FDC086
L6652;#BF5B17
L9476;#7FC97F
L6292;#FC8D62
L1680;#E5D8BD
L6285;#BEBADA
L2220;#E41A1C
L9814;#80B1D3
L6285;#377EB8
L9631;#FCCDE5
L1353;#D9D9D9

Note that L1420 is repeated with two different colors (lines 1 and 3). 
If you remove the first everything works as expected. I presume. But the 
fact is that the interface should spot this mistakes when loading data 
and it didn't! I'll look at it as soon as possible. What worries me is 
that the server where the program is located is apparently down and 
shouldn't be. The software was published in Bioinformatics (see early 
view for citing, please!)

Regards

Antonio

**Comment by sairum** [comment]
I've committed a fix to ignore repeated names in the Groups's classification file. Please try it with your original data (with the repeated group L1420) just to see if it works. Note that I still have to push these changes to the online version of tcsBU, but I currently I do not have access to it (it may take some days)

**Comment by josephhughes** [comment]
Hi @sairum,

Thanks for your prompt response. I have removed the duplicate Groups but I am still getting something odd happening for the legend. The attached screenshot shows that L1353 and L9631 re the wrong colors.
Let me know when you've managed to push the changes.

Cheers,
Joseph
<img width="1037" alt="screen shot 2015-11-20 at 10 41 45" src="https://cloud.githubusercontent.com/assets/359553/11297973/b4d451f4-8f73-11e5-8425-2e18cac80337.png">

**Comment by sairum** [comment]
Humm, I see. Are you using the online version or the code from github?

**Comment by josephhughes** [comment]
Hi @sairum,

It works fine now. Thanks for your help.

Joseph
